In [1]:
import pandas as pd

In [2]:
test = pd.read_csv('test.csv')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
test.head(10)

,bodyType,brand,car_url,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,image,mileage,modelDate,model_info,model_name,name,numberOfDoors,parsing_unixtime,priceCurrency,productionDate,sell_id,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,Владение,ПТС,Привод,Руль,Состояние,Таможня
0,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,синий,NaN,"Все автомобили, представленные в продаже, прох...",1.2 LTR,105 N12,"{""engine-proof"":true,""tinted-glass"":true,""airb...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,74000,2013,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.2 AMT (105 л.с.),5,1603226273,RUB,2014,1100575026,"{""id"":""10373605"",""displacement"":1197,""engine_t...",LIFTBACK ROBOT 1.2,роботизированная,EUROPEAN,3 или более,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
1,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,чёрный,NaN,ЛОТ: 01217195\nАвтопрага Север\nДанный автомоб...,1.6 LTR,110 N12,"{""cruise-control"":true,""asr"":true,""esp"":true,""...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,60563,2017,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.6 MT (110 л.с.),5,1603226277,RUB,2017,1100549428,"{""id"":""20913311"",""displacement"":1598,""engine_t...",LIFTBACK MECHANICAL 1.6,механическая,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
2,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/superb/11...,серый,"{""id"":""20026336"",""name"":""Ambition"",""available_...","Все автомобили, представленные в продаже, прох...",1.8 LTR,152 N12,"{""cruise-control"":true,""tinted-glass"":true,""es...",бензин,https://avatars.mds.yandex.net/get-autoru-vos/...,88000,2013,"{""code"":""SUPERB"",""name"":""Superb"",""ru_name"":""Су...",SUPERB,DSG 1.8 AMT (152 л.с.),5,1603226280,RUB,2014,1100658222,"{""id"":""20026323"",""nameplate"":""DSG"",""displaceme...",LIFTBACK ROBOT 1.8,роботизированная,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
3,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,коричневый,"{""id"":""20803582"",""name"":""Ambition"",""available_...",КОМПЛЕКТ ЗИМНЕЙ (ЛЕТНЕЙ) РЕЗИНЫ ПО СЕЗОНУ В ПО...,1.6 LTR,110 N12,"{""cruise-control"":true,""roller-blind-for-rear-...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,95000,2013,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.6 AT (110 л.с.),5,1603226284,RUB,2014,1100937408,"{""id"":""20105521"",""displacement"":1598,""engine_t...",LIFTBACK AUTOMATIC 1.6,автоматическая,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
4,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,белый,NaN,ЛОТ: 01220889\nАвтопрага Север\n\nВы можете по...,1.8 LTR,152 N12,"{""cruise-control"":true,""asr"":true,""esp"":true,""...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,58536,2008,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.8 AT (152 л.с.),5,1603226288,RUB,2012,1101037972,"{""id"":""4561004"",""displacement"":1798,""engine_ty...",LIFTBACK AUTOMATIC 1.8,автоматическая,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
5,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia_r...,серый,"{""id"":""5011515"",""name"":""RS"",""available_options...",Продаю свой автомобиль! Автомобиль полностью и...,2.0 LTR,200 N12,"{""cruise-control"":true,""tinted-glass"":true,""es...",бензин,https://avatars.mds.yandex.net/get-autoru-vos/...,172000,2008,"{""code"":""OCTAVIA_RS"",""name"":""Octavia RS"",""ru_n...",OCTAVIA_RS,2.0 AMT (200 л.с.),5,1603226291,RUB,2012,1100912634,"{""id"":""5009158"",""displacement"":1984,""engine_ty...",LIFTBACK ROBOT 2.0,роботизированная,EUROPEAN,3 или более,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
6,внедорожник 5 дв.,SKODA,https://auto.ru/cars/used/sale/skoda/yeti/1101...,пурпурный,"{""id"":""20069264"",""name"":""Elegance"",""available_...",- выгода 60 000 рублей при покупке авто в Trad...,1.8 LTR,152 N12,"{""cruise-control"":true,""tinted-glass"":true,""es...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,107000,2009,"{""code"":""YETI"",""name"":""Yeti"",""ru_name"":""Йети"",...",YETI,1.8 AMT (152 л.с.) 4WD,5,1603226295,RUB,2012,1101228730,"{""id"":""20089129"",""displacement"":1798,""engine_t...",ALLROAD_5_DOORS ROBOT 1.8,роботизированная,EUROPEAN,1 владелец,NaN,Оригинал,полный,Левый,Не требует ремонта,Растаможен
7,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,белый,NaN,ЛОТ: 01214644\nАвтопрага Юг\n\nВы можете получ...,1.6 LTR,102 N12,"{""asr"":true,""tinted-glass"":true,""airbag-driver...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,226706,2008,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.6 MT (102 л.с.),5,1603226299,RUB,2011,1100165896,"{""id"":""4561001"",""displacement"":1595,""engine_ty...",LIFTBACK MECHANICAL 1.6,механическая,EUROPEAN,3 или более,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
8,внедорожник 5 дв.,SKODA,https://auto.ru/cars/used/sale/skoda/kodiaq/11...,бежевый,NaN,ЛОТ: 01217938\nАвтопрага Север\nДанный автомоб...,1.4 LTR,150 N12,"{""cruise-control"":true,""asr"":true,""esp"":true,""...",бензин,https://avatars.mds.yandex.net/get-autoru-vos/...,9706,2016,"{""code"":""KODIAQ"",""name"":""Kodiaq"",""ru_name"":""Ко...",KODIAQ,1.4 MT (150 л.с.) 4WD,5,1603226303,RUB,2019,1100768262,"{""id"":""20839186"",""displacement"":1395,""engine_t...",ALLROAD_5_DOORS MECHANICAL 1.4,механическая,EUROPEAN,1 владелец,NaN,Оригинал,полный,Левый,Не требует ремонта,Растаможен
9,внедорожник 5 дв.,SKODA,https://auto.ru/cars/used/sale/skoda/yeti/1101...,белый,NaN,ЛОТ: 01222831\nАвтопрага Север\n\nВы можете по...,1.8 LTR,152 N12,"{""asr"":true,""tinted-glass"":true,""esp"":true,""ai...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,37361,2009,"{""code"":""YETI"",""name"":""Yeti"",""ru_name"":""Йети"",...",YETI,1.8 MT (152 л.с.) 4WD,5,1603226307,RUB,2012,1101218501,"{""id"":""6038953"",""displacement"":1798,""engine_ty...",ALLROAD_5_DOORS MECHANICAL 1.8,механическая,EUROPEAN,1 владелец,NaN,Оригинал,полный,Левый,Не требует ремонта,Растаможен

In [5]:
train = pd.read_csv('parsed_data.csv')

In [6]:
train.head(10)

,bodyType,brand,car_url,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,image,mileage,modelDate,model_info,model_name,name,numberOfDoors,parsing_unixtime,priceCurrency,productionDate,sell_id,super_gen,vehicleConfiguration,vehicleTransmission,vendor,owners_number,ownership_period,pts,gear_type,steering_wheel,state,custom_cleared,price
0,Родстер,AC,https://auto.ru/cars/used/sale/ac/COBRA/108956...,EE1D19,"{'id': '20465465', 'body_type': 'ROADSTER', 'd...",Не участвовала в ДТП. очень шустрый легкий езд...,4.9,326,"{'alloy-wheel-disks': True, '14-inch-wheels': ...",GASOLINE,NaN,13500,1990,"{'code': 'COBRA', 'name': 'Cobra', 'ru_name': ...",COBRA,4.9 MT (326 л.с.),2,1620108789,RUB,2001,1089566651,"{'id': '20331849', 'name': 'Mk IV', 'year_from...",ROADSTER MECHANICAL 4.9,MECHANICAL,EUROPEAN,2.0,0,ORIGINAL,REAR_DRIVE,LEFT,True,True,1800000.0
1,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11027...,040001,"{'id': '20079921', 'body_type': 'ALLROAD_5_DOO...",Advance максимальная комплектация.\n7 мест.\nД...,3.5,290,"{'esp': True, 'usb': True, 'windcleaner-heat':...",GASOLINE,NaN,103000,2013,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.5 AT (290 л.с.) 4WD,5,1620108789,RUB,2014,1102773584,"{'id': '10382709', 'name': 'III', 'ru_name': '...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,1.0,85,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,2450000.0
2,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11033...,CACECB,"{'id': '20805159', 'body_type': 'ALLROAD_5_DOO...","Автомобиль без пробега по России из США, выпус...",3.5,290,"{'cruise-control': True, 'asr': True, 'tinted-...",GASOLINE,NaN,55500,2016,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.5 AT (290 л.с.) 4WD,5,1620108789,RUB,2017,1103368840,"{'id': '20805126', 'name': 'III Рестайлинг 2',...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,1.0,8,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,2790000.0
3,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11023...,FAFBFB,"{'id': '20079921', 'body_type': 'ALLROAD_5_DOO...",Внимание! Только для клиентов AVILON Автомобил...,3.5,290,"{'cruise-control': True, 'esp': True, 'usb': T...",GASOLINE,NaN,124592,2013,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.5 AT (290 л.с.) 4WD,5,1620108789,RUB,2014,1102331288,"{'id': '10382709', 'name': 'III', 'ru_name': '...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,2.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,1790000.0
4,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11033...,040001,"{'id': '20079921', 'body_type': 'ALLROAD_5_DOO...",💸Выгода до 100 000 рублей при покупке в кредит...,3.5,290,"{'tinted-glass': True, 'esp': True, 'adaptive-...",GASOLINE,NaN,155000,2013,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.5 AT (290 л.с.) 4WD,5,1620108789,RUB,2014,1103389918,"{'id': '10382709', 'name': 'III', 'ru_name': '...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,3.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,1715000.0
5,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11032...,97948F,"{'id': '2305177', 'body_type': 'ALLROAD_5_DOOR...",Продажа от официального дилера ГК «АВТОМИР».\n...,3.7,300,"{'alloy-wheel-disks': True, 'esp': True, 'airb...",GASOLINE,NaN,318078,2006,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.7 AT (300 л.с.) 4WD,5,1620108789,RUB,2007,1103267445,"{'id': '2305176', 'name': 'II', 'ru_name': '2'...",ALLROAD_5_DOORS AUTOMATIC 3.7,AUTOMATIC,JAPANESE,4.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,747000.0
6,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11034...,97948F,"{'id': '4841634', 'body_type': 'ALLROAD_5_DOOR...","Много нового, Миг перебрал АКПП, есть недостат...",3.5,260,"{'engine-proof': True, 'cruise-control': True,...",GASOLINE,NaN,200000,2000,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.5 AT (260 л.с.) 4WD,5,1620108789,RUB,2005,1103400278,"{'id': '4841633', 'name': 'I', 'ru_name': '1',...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,3.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,530000.0
7,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/RDX/11031...,040001,"{'id': '20079930', 'body_type': 'ALLROAD_5_DOO...",ПТС оригинал\n\n\n\n\nАвтомобиль продается от ...,3.5,277,"{'cruise-control': True, 'tinted-glass': True,...",GASOLINE,NaN,192500,2013,"{'code': 'RDX', 'name': 'RDX', 'ru_name': 'РДХ...",RDX,3.5 AT (277 л.с.) 4WD,5,1620108789,RUB,2014,1103167715,"{'id': '20079928', 'name': 'II', 'ru_name': '2...",ALLROAD_5_DOORS AUTOMATIC 3.5,AUTOMATIC,JAPANESE,2.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,1915000.0
8,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/MDX/11025...,CACECB,"{'id': '2305177', 'body_type': 'ALLROAD_5_DOOR...",Продаю отличную машину аналог Хонды Пилот толь...,3.7,300,"{'asr': True, 'tinted-glass': True, 'esp': Tru...",GASOLINE,NaN,168800,2006,"{'code': 'MDX', 'name': 'MDX', 'ru_name': 'мдх...",MDX,3.7 AT (300 л.с.) 4WD,5,1620108789,RUB,2007,1102511738,"{'id': '2305176', 'name': 'II', 'ru_name': '2'...",ALLROAD_5_DOORS AUTOMATIC 3.7,AUTOMATIC,JAPANESE,4.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,670000.0
9,Внедорожник 5 дв.,ACURA,https://auto.ru/cars/used/sale/acura/RDX/11030...,97948F,"{'id': '6417886', 'body_type': 'ALLROAD_5_DOOR...",✪ 1 Владелец\n✪ ПТС оригинал\n✪ Автомобиль ухо...,2.3,240,"{'cruise-control': True, 'esp': True, 'electro...",GASOLINE,NaN,133361,2009,"{'code': 'RDX', 'name': 'RDX', 'ru_name': 'РДХ...",RDX,2.3 AT (240 л.с.) 4WD,5,1620108789,RUB,2010,1103003364,"{'id': '6417882', 'name': 'I Рестайлинг', 'ru_...",ALLROAD_5_DOORS AUTOMATIC 2.3,AUTOMATIC,JAPANESE,1.0,0,ORIGINAL,ALL_WHEEL_DRIVE,LEFT,True,True,920000.0

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34686 entries, 0 to 34685
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   bodyType              34686 non-null  object
 1   brand                 34686 non-null  object
 2   car_url               34686 non-null  object
 3   color                 34686 non-null  object
 4   complectation_dict    6418 non-null   object
 5   description           34686 non-null  object
 6   engineDisplacement    34686 non-null  object
 7   enginePower           34686 non-null  object
 8   equipment_dict        24690 non-null  object
 9   fuelType              34686 non-null  object
 10  image                 34686 non-null  object
 11  mileage               34686 non-null  int64
 12  modelDate             34686 non-null  int64
 13  model_info            34686 non-null  object
 14  model_name            34686 non-null  object
 15  name                  34686 non-null  object
 16  numberOfDoors         34686 non-null  int64
 17  parsing_unixtime      34686 non-null  int64
 18  priceCurrency         34686 non-null  object
 19  productionDate        34686 non-null  int64
 20  sell_id               34686 non-null  int64
 21  super_gen             34686 non-null  object
 22  vehicleConfiguration  34686 non-null  object
 23  vehicleTransmission   34686 non-null  object
 24  vendor                34686 non-null  object
 25  Владельцы             34686 non-null  object
 26  Владение              11995 non-null  object
 27  ПТС                   34685 non-null  object
 28  Привод                34686 non-null  object
 29  Руль                  34686 non-null  object
 30  Состояние             34686 non-null  object
 31  Таможня               34686 non-null  object
dtypes: int64(6), object(26)
memory usage: 8.5+ MB

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52571 entries, 0 to 52570
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   bodyType              52571 non-null  object
 1   brand                 52571 non-null  object
 2   car_url               52571 non-null  object
 3   color                 52571 non-null  object
 4   complectation_dict    52571 non-null  object
 5   description           50805 non-null  object
 6   engineDisplacement    52571 non-null  float64
 7   enginePower           52571 non-null  int64
 8   equipment_dict        52571 non-null  object
 9   fuelType              52571 non-null  object
 10  image                 0 non-null      float64
 11  mileage               52571 non-null  int64
 12  modelDate             52571 non-null  int64
 13  model_info            52571 non-null  object
 14  model_name            52571 non-null  object
 15  name                  52571 non-null  object
 16  numberOfDoors         52571 non-null  int64
 17  parsing_unixtime      52571 non-null  int64
 18  priceCurrency         52346 non-null  object
 19  productionDate        52571 non-null  int64
 20  sell_id               52571 non-null  int64
 21  super_gen             52571 non-null  object
 22  vehicleConfiguration  52571 non-null  object
 23  vehicleTransmission   52571 non-null  object
 24  vendor                52571 non-null  object
 25  owners_number         52570 non-null  float64
 26  ownership_period      52571 non-null  int64
 27  pts                   52569 non-null  object
 28  gear_type             52571 non-null  object
 29  steering_wheel        52571 non-null  object
 30  state                 52571 non-null  bool
 31  custom_cleared        52571 non-null  bool
 32  price                 52346 non-null  float64
dtypes: bool(2), float64(4), int64(8), object(19)
memory usage: 12.5+ MB

1. переименовать колонки +
2. bodytype - в нижний регистр - категории +
3. brand - без преобразований +
4. цвет - перевести на русский +
5. комплектацию и описание - пока не трогаем (у комлпектации не совпадают ключи)!!!!!!
6. enginedisplacement - убрать LTR +
7. enginepower - убрать N12 +
8. equipment - вытащить все признаки, сделать бинарными !!!!
9. fuel - привести к русскому +
10. mileage - без преобразований +
11. model_info - вопрос про удаление ---
12. model_name - без преобразований +
13. name - вытащить лошадиные силы !!!!
14. кол-во дверей - без преобразований +
15. валюта - удаление +
16. год производства - без преобразований +
17. super_gen - пока не трогаем (не совпадают ключи) !!!!!
18. конфигурация - вытащить коробку !!!!
19. vendor - без преобразований +
20. владельцы - у трейн привести в категории 1, 2, 3. у тест убрать слова +
21. владение - у тест привести к месяцам +
22. ПТС - сделать бинарным +
23. привод - перевести на русский одинаково +
24. руль - сделать бинарным +
25. состояние и таможня - под удаление +

In [9]:
test.rename(columns={'Владельцы': 'owners_number', 'Владение': 'ownership_period',
                     'ПТС': 'pts', 'Привод': 'gear_type',
                     'Руль': 'steering_wheel', 'Состояние': 'state', 'Таможня': 'custom_cleared'}, inplace=True)

In [10]:
train.steering_wheel.value_counts()

LEFT     51610
RIGHT      961
Name: steering_wheel, dtype: int64

In [11]:
train.steering_wheel = train.steering_wheel.apply(lambda x: 1 if x == 'LEFT' else 0)

In [12]:
test.steering_wheel.value_counts()

Левый     33287
Правый     1399
Name: steering_wheel, dtype: int64

In [13]:
test.steering_wheel = test.steering_wheel.apply(lambda x: 1 if x == 'Левый' else 0)

In [14]:
train.pts.value_counts()

ORIGINAL     46317
DUPLICATE     6252
Name: pts, dtype: int64

In [15]:
train.pts = train.pts.apply(lambda x: 1 if x == 'ORIGINAL' else 0)

In [16]:
test.pts.value_counts()

Оригинал    30098
Дубликат     4587
Name: pts, dtype: int64

In [17]:
test.pts = test.pts.apply(lambda x: 1 if x == 'Оригинал' else 0)

In [18]:
train = train.drop(['priceCurrency', 'state', 'custom_cleared'], axis=1)

In [19]:
test = test.drop(['priceCurrency', 'state', 'custom_cleared'], axis=1)

In [20]:
train.color.value_counts()

040001    14041
FAFBFB    10291
97948F     7010
CACECB     5288
0000CC     4926
EE1D19     2781
200204     2494
007F00     1685
C49648     1208
22A0F8      767
FFD600      487
660099      471
4A2197      383
DEA522      381
FF8649      342
FFC0CB       16
Name: color, dtype: int64

In [21]:
test.color.value_counts()

чёрный         11010
белый           6133
серебристый     4113
серый           3984
синий           3289
красный         1531
коричневый      1501
зелёный          952
бежевый          639
голубой          457
золотистый       266
пурпурный        254
фиолетовый       219
жёлтый           194
оранжевый        131
розовый           13
Name: color, dtype: int64

In [22]:
color = {'040001' : 'чёрный',
        'FAFBFB': 'белый',
        '97948F': 'серебристый',
        'CACECB': 'серый',
        '0000CC': 'синий',
        'EE1D19': 'красный',
        '200204': 'коричневый',
        '007F00': 'зелёный',
        'C49648': 'бежевый',
        '22A0F8': 'голубой',
        'FFD600': 'золотистый',
        '660099': 'пурпурный',
        '4A2197': 'фиолетовый',
        'DEA522': 'жёлтый',
        'FF8649': 'оранжевый',
        'FFC0CB': 'розовый'
        }

In [23]:
train.color = train.color.map(color)

In [24]:
test.bodyType.value_counts()

седан                      13147
внедорожник 5 дв.          12228
лифтбек                     2232
хэтчбек 5 дв.               2124
универсал 5 дв.             1276
минивэн                      995
купе                         824
компактвэн                   489
хэтчбек 3 дв.                485
пикап двойная кабина         280
купе-хардтоп                 158
внедорожник 3 дв.            115
родстер                       99
фургон                        97
кабриолет                     90
седан-хардтоп                 12
микровэн                       7
седан 2 дв.                    6
лимузин                        6
пикап одинарная кабина         5
пикап полуторная кабина        5
внедорожник открытый           3
тарга                          2
фастбек                        1
Name: bodyType, dtype: int64

In [25]:
train.bodyType = train.bodyType.apply(lambda x: x.lower())

In [26]:
train.bodyType = train.bodyType.apply(lambda x: x.split(' ')[0])

In [27]:
train.bodyType.value_counts()

седан            18769
внедорожник      17934
хэтчбек           7333
универсал         2518
лифтбек           1859
минивэн           1122
компактвэн        1009
купе               994
пикап              315
фургон             283
купе-хардтоп       151
кабриолет          114
родстер            107
микровэн            23
фастбек             18
седан-хардтоп        8
лимузин              6
спидстер             5
тарга                3
Name: bodyType, dtype: int64

In [28]:
test.bodyType = test.bodyType.apply(lambda x: x.split(' ')[0])

In [29]:
test.bodyType.value_counts()

седан            13153
внедорожник      12346
хэтчбек           2609
лифтбек           2232
универсал         1276
минивэн            995
купе               824
компактвэн         489
пикап              290
купе-хардтоп       158
родстер             99
фургон              97
кабриолет           90
седан-хардтоп       12
микровэн             7
лимузин              6
тарга                2
фастбек              1
Name: bodyType, dtype: int64

In [30]:
test.engineDisplacement = test.engineDisplacement.apply(lambda x: x[:-4])

!!! пустые строки 55

In [31]:
test.enginePower = test.enginePower.apply(lambda x: x[:-4])

In [32]:
test.fuelType.value_counts()

бензин     28601
дизель      5800
гибрид       223
электро       55
газ            7
Name: fuelType, dtype: int64

In [33]:
train.fuelType.value_counts()

GASOLINE    44519
DIESEL       7709
HYBRID        212
ELECTRO       123
LPG             8
Name: fuelType, dtype: int64

In [34]:
fuel = {'GASOLINE': 'бензин',
       'DIESEL': 'дизель',
       'HYBRID': 'гибрид',
       'ELECTRO': 'электро',
       'LPG': 'газ'}

In [35]:
train.fuelType = train.fuelType.map(fuel)

In [36]:
train.fuelType.value_counts()

бензин     44519
дизель      7709
гибрид       212
электро      123
газ            8
Name: fuelType, dtype: int64

In [37]:
train.gear_type.value_counts()

FORWARD_CONTROL    27377
ALL_WHEEL_DRIVE    19631
REAR_DRIVE          5563
Name: gear_type, dtype: int64

In [38]:
test.gear_type.value_counts()

передний    15565
полный      15020
задний       4101
Name: gear_type, dtype: int64

In [39]:
gear_type = {
    'FORWARD_CONTROL': 'передний',
    'ALL_WHEEL_DRIVE': 'полный',
    'REAR_DRIVE': 'задний'
}

In [40]:
train.gear_type = train.gear_type.map(gear_type)

In [41]:
train.owners_number.value_counts()

1.0    17864
2.0    14169
3.0    12571
4.0     7966
Name: owners_number, dtype: int64

In [42]:
test.owners_number.value_counts()

3 или более    15957
1 владелец      9459
2 владельца     9270
Name: owners_number, dtype: int64

In [43]:
train.owners_number = train.owners_number.apply(lambda x: 3.0 if x == 4.0 else x)
train.owners_number = train.owners_number.fillna(1.0)
train.owners_number = train.owners_number.apply(lambda x: int(x))

In [44]:
test.owners_number = test.owners_number.apply(lambda x: x[0])

In [45]:
test.ownership_period.value_counts()

1 год и 10 месяцев      209
2 года                  197
1 год                   194
1 год и 1 месяц         193
1 год и 2 месяца        187
2 года и 1 месяц        182
1 год и 11 месяцев      179
1 год и 6 месяцев       171
1 год и 4 месяца        169
2 года и 4 месяца       168
11 месяцев              167
2 года и 2 месяца       167
9 месяцев               166
10 месяцев              166
1 год и 5 месяцев       165
2 года и 5 месяцев      160
1 год и 7 месяцев       154
1 год и 3 месяца        154
2 года и 3 месяца       152
3 года                  146
1 год и 9 месяцев       144
3 года и 2 месяца       144
2 года и 10 месяцев     143
3 года и 1 месяц        142
7 месяцев               139
1 год и 8 месяцев       134
2 года и 6 месяцев      134
2 года и 7 месяцев      133
3 года и 5 месяцев      131
2 года и 11 месяцев     131
3 года и 7 месяцев      130
2 года и 8 месяцев      126
2 года и 9 месяцев      123
4 года                  122
8 месяцев               121
3 года и 6 месяцев      121
3 года и 3 месяца       121
5 лет и 10 месяцев      117
3 года и 4 месяца       116
3 года и 10 месяцев     111
4 года и 4 месяца       110
4 месяца                109
4 года и 6 месяцев      108
3 года и 8 месяцев      108
4 года и 1 месяц        107
3 года и 11 месяцев     104
4 года и 2 месяца        98
3 года и 9 месяцев       97
5 месяцев                89
4 года и 10 месяцев      88
6 лет и 1 месяц          87
4 года и 5 месяцев       87
6 лет и 5 месяцев        87
4 года и 9 месяцев       86
6 лет и 6 месяцев        86
3 месяца                 82
4 года и 11 месяцев      81
6 лет и 8 месяцев        80
4 года и 7 месяцев       80
5 лет и 9 месяцев        78
6 лет и 2 месяца         76
5 лет и 1 месяц          75
5 лет и 11 месяцев       75
4 года и 3 месяца        73
4 года и 8 месяцев       73
5 лет                    71
2 месяца                 70
7 лет и 2 месяца         69
5 лет и 3 месяца         69
5 лет и 7 месяцев        68
6 лет и 7 месяцев        68
5 лет и 8 месяцев        67
7 лет и 5 месяцев        66
7 лет и 6 месяцев        66
1 месяц                  65
6 лет и 10 месяцев       65
7 лет и 4 месяца         65
6 лет и 9 месяцев        61
5 лет и 5 месяцев        61
6 лет и 3 месяца         60
8 лет                    60
6 месяцев                60
5 лет и 4 месяца         60
6 лет и 4 месяца         59
7 лет                    59
6 лет и 11 месяцев       59
5 лет и 2 месяца         58
8 лет и 5 месяцев        57
5 лет и 6 месяцев        57
6 лет                    57
7 лет и 7 месяцев        56
7 лет и 1 месяц          55
7 лет и 9 месяцев        53
8 лет и 7 месяцев        50
8 лет и 2 месяца         49
8 лет и 6 месяцев        49
8 лет и 4 месяца         48
7 лет и 3 месяца         47
8 лет и 10 месяцев       47
9 лет и 1 месяц          45
7 лет и 11 месяцев       45
8 лет и 3 месяца         44
8 лет и 11 месяцев       44
7 лет и 8 месяцев        43
7 лет и 10 месяцев       40
8 лет и 8 месяцев        39
8 лет и 1 месяц          39
9 лет                    38
8 лет и 9 месяцев        37
9 лет и 10 месяцев       33
11 лет и 10 месяцев      33
9 лет и 2 месяца         32
9 лет и 4 месяца         31
9 лет и 5 месяцев        31
9 лет и 7 месяцев        30
9 лет и 6 месяцев        28
9 лет и 8 месяцев        25
10 лет и 1 месяц         25
10 лет и 4 месяца        25
9 лет и 11 месяцев       24
9 лет и 3 месяца         24
10 лет и 2 месяца        23
10 лет и 6 месяцев       23
12 лет и 4 месяца        22
10 лет и 7 месяцев       22
10 лет                   22
9 лет и 9 месяцев        22
10 лет и 9 месяцев       21
10 лет и 5 месяцев       20
10 лет и 10 месяцев      20
12 лет                   19
12 лет и 2 месяца        18
11 лет и 1 месяц         17
11 лет и 3 месяца        17
10 лет и 8 месяцев       17
11 лет и 5 месяцев       17
12 лет и 5 месяцев       17
12 лет и 10 месяцев      17
10 лет и 3 месяца        17
12 лет и 8 месяцев       17
11 лет и 11 месяцев      16
12 лет и 7 месяцев       15
13 лет и 4 месяца        14
12 лет и 9 месяцев       13
12 лет и 6 месяцев       13
11 лет                   13
11 лет и 9 месяцев       13
12 лет и 3 месяца        12
13 лет и 6 месяцев       12
13 лет и 9 месяцев       12
13 лет и 5 месяцев       11
12 лет и 11 месяцев      11
11 лет и 7 месяцев       11
11 лет и 6 месяцев       11
13 лет и 8 месяцев       11
13 лет и 2 месяца        11
14 лет и 4 месяца        10
12 лет и 1 месяц         10
10 лет и 11 месяцев      10
14 лет                    9
11 лет и 4 месяца         9
13 лет                    9
13 лет и 3 месяца         9
13 лет и 10 месяцев       9
14 лет и 5 месяцев        9
13 лет и 1 месяц          9
11 лет и 2 месяца         9
15 лет и 10 месяцев       9
11 лет и 8 месяцев        8
13 лет и 11 месяцев       7
15 лет и 9 месяцев        7
14 лет и 1 месяц          7
14 лет и 9 месяцев        7
13 лет и 7 месяцев        6
14 лет и 6 месяцев        6
15 лет и 3 месяца         6
15 лет                    6
14 лет и 7 месяцев        6
14 лет и 11 месяцев       6
14 лет и 10 месяцев       6
15 лет и 2 месяца         6
17 лет и 4 месяца         5
15 лет и 1 месяц          5
15 лет и 4 месяца         5
15 лет и 6 месяцев        5
15 лет и 11 месяцев       5
16 лет и 2 месяца         5
17 лет и 5 месяцев        5
15 лет и 7 месяцев        4
14 лет и 2 месяца         4
16 лет и 1 месяц          4
16 лет и 6 месяцев        4
14 лет и 3 месяца         4
18 лет                    3
20 лет и 10 месяцев       3
17 лет и 3 месяца         3
16 лет и 7 месяцев        3
15 лет и 5 месяцев        3
20 лет и 4 месяца         3
16 лет и 9 месяцев        3
20 лет и 3 месяца         3
20 лет и 9 месяцев        3
16 лет и 4 месяца         3
17 лет и 7 месяцев        3
17 лет и 1 месяц          3
17 лет и 6 месяцев        3
19 лет и 8 месяцев        3
19 лет и 2 месяца         2
22 года и 2 месяца        2
17 лет                    2
22 года и 6 месяцев       2
24 года и 3 месяца        2
17 лет и 10 месяцев       2
19 лет и 10 месяцев       2
18 лет и 11 месяцев       2
20 лет и 11 месяцев       2
19 лет и 6 месяцев        2
22 года и 10 месяцев      2
17 лет и 2 месяца         2
23 года и 3 месяца        2
27 лет и 9 месяцев        2
16 лет                    2
18 лет и 3 месяца         2
20 лет и 2 месяца         2
23 года и 6 месяцев       2
18 лет и 6 месяцев        2
16 лет и 11 месяцев       2
20 лет и 1 месяц          2
16 лет и 8 месяцев        2
25 лет и 9 месяцев        2
16 лет и 10 месяцев       2
20 лет и 7 месяцев        2
18 лет и 1 месяц          2
18 лет и 8 месяцев        2
23 года и 4 месяца        2
14 лет и 8 месяцев        2
23 года и 2 месяца        1
26 лет и 3 месяца         1
20 лет и 5 месяцев        1
21 год и 8 месяцев        1
21 год и 9 месяцев        1
21 год и 11 месяцев       1
21 год и 6 месяцев        1
28 лет и 8 месяцев        1
18 лет и 4 месяца         1
18 лет и 5 месяцев        1
21 год и 2 месяца         1
18 лет и 9 месяцев        1
26 лет и 7 месяцев        1
18 лет и 10 месяцев       1
19 лет                    1
19 лет и 5 месяцев        1
23 года и 9 месяцев       1
18 лет и 2 месяца         1
24 года и 2 месяца        1
21 год и 4 месяца         1
17 лет и 9 месяцев        1
18 лет и 7 месяцев        1
34 года и 2 месяца        1
16 лет и 5 месяцев        1
19 лет и 11 месяцев       1
16 лет и 3 месяца         1
26 лет и 5 месяцев        1
31 год и 5 месяцев        1
29 лет и 11 месяцев       1
20 лет                    1
22 года и 9 месяцев       1
19 лет и 9 месяцев        1
42 года и 10 месяцев      1
22 года и 3 месяца        1
20 лет и 8 месяцев        1
29 лет и 9 месяцев        1
19 лет и 7 месяцев        1
19 лет и 4 месяца         1
15 лет и 8 месяцев        1
Name: ownership_period, dtype: int64

In [46]:
import re
import datetime

In [47]:
pattern_year = re.compile('\d+\s[годалт]+')

In [48]:
pattern_month = re.compile('\d+\s[мсяцв]+')

In [49]:
pattern_digit = re.compile('\d+')

In [50]:
test['year'] = test['ownership_period'].apply(lambda x: str(pattern_year.findall(str(x))))
test['month'] = test['ownership_period'].apply(lambda x: str(pattern_month.findall(str(x))))
test['year'] = test['year'].apply(lambda x: str(pattern_digit.findall(str(x))))
test['year'] = test['year'].apply(lambda x: x[2:-2])
test['month'] = test['month'].apply(lambda x: str(pattern_digit.findall(str(x))))
test['month'] = test['month'].apply(lambda x: x[2:-2])

In [51]:
test['year'] = test['year'].apply(lambda x: 0 if x == '' else int(x))
test['month'] = test['month'].apply(lambda x: 0 if x == '' else int(x))

In [52]:
test['ownership'] = test.apply(lambda x: (x['year']*12) + x['month'], axis=1)

In [53]:
test = test.drop(['ownership_period'], axis = 1)

In [54]:
train.rename(columns={'ownership_period': 'ownership'}, inplace=True)