In [1]:
import pandas as pd

In [2]:
tables = pd.read_html('https://www.finam.ru/quotes/stocks/russia/')

In [3]:
# Изучаем содержимое объекта tables
df = tables[0]
df

,Unnamed: 0,Инструмент,"Посл. сделка, ₽",% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,+МосЭнергоПотенциал:+7%,2.045 ₽,-0.7%,2.0620,2.101,2.045,2.0595,35 483 000,18.09 18:45
1,NaN,Activision,6087,3.7%,5881.0000,6088.000,5881.000,5870.0000,742,18.09 23:39
2,NaN,AGRO-гдрПотенциал:+24%,743.4 ₽,-0.59%,750.0000,753.800,740.400,747.8000,39 456,18.09 18:49
3,NaN,Amazon,221813,-2.37%,220500.0000,229466.000,220500.000,227200.0000,100,18.09 22:02
4,NaN,AMD Inc.,5685,-1.22%,5747.0000,5840.000,5599.000,5755.0000,3 295,18.09 23:38
5,NaN,Apple,8142,-2.99%,8250.0000,8417.000,8044.000,8393.0000,10 910,18.09 23:49
6,NaN,ATT,2193,0%,2193.0000,2210.000,2190.000,2193.0000,1 645,18.09 22:50
7,NaN,Boeing,12275,-2.61%,12655.0000,12800.000,12220.000,12604.0000,3 308,18.09 23:49
8,NaN,Disney,9755,-0.21%,9776.0000,9881.000,9710.000,9776.0000,640,18.09 22:59
9,NaN,ENPL-гдр,531.2 ₽,0.45%,NaN,NaN,NaN,531.2000,NaN,14.04 18:49
10,NaN,ETLN-гдр,121.06,0.48%,121.8000,121.880,120.100,120.4800,234 850,18.09 18:47
11,NaN,ExxonMobil,2780,-2.59%,2839.0000,2858.000,2780.000,2854.0000,2 864,18.09 23:15
12,NaN,Facebook,19182,-0.25%,19429.0000,19595.000,19000.000,19230.0000,650,18.09 23:14
13,NaN,FIVE-гдр,2821.5 ₽,0.43%,2810.0000,2861.000,2786.000,2809.5000,303 264,18.09 23:49
14,NaN,Google C,110562,-1.5%,114593.0000,114593.000,109000.000,112250.0000,233,18.09 22:57
15,NaN,iАвиастКао,0.4485 ₽,-1.64%,0.4595,0.462,0.420,0.4560,7 598 000,18.09 18:36
16,NaN,iДонскЗР,2115 ₽,-0.47%,2125.0000,2150.000,2115.000,2125.0000,25,18.09 16:05
17,NaN,iДонскЗР п,1920 ₽,0%,1940.0000,1950.000,1910.000,1920.0000,178,18.09 17:42
18,NaN,iИСКЧ ао,26.52 ₽,-2.96%,27.3000,27.590,26.500,27.3300,303 800,18.09 18:47
19,NaN,iММЦБ ао,603.5,-0.08%,605.5000,605.500,600.500,604.0000,1 356,18.09 18:35
20,NaN,iНПОНаука,201.2 ₽,0.6%,198.4000,213.000,194.000,200.0000,7 750,18.09 18:47
21,NaN,iФармсинтз,7.18 ₽,-0.28%,7.2200,7.250,7.155,7.2000,319 000,18.09 18:45
22,NaN,Intel,3790,0.29%,3770.0000,3810.000,3716.000,3779.0000,3 509,18.09 23:38
23,NaN,iQIWI,1240 ₽,-2.75%,1258.0000,1260.000,1240.000,1275.0000,75 643,18.09 18:49
24,NaN,MAIL-гдр,2220,-0.09%,2192.0000,2224.000,2172.400,2222.0000,348 122,18.09 18:49
25,NaN,Master A,25330,-0.83%,25611.0000,25825.000,25330.000,25543.0000,80,18.09 21:03
26,NaN,McDonald's,16700,-0.48%,16678.0000,16869.000,16678.000,16781.0000,205,18.09 22:50
27,NaN,Micron,3862,0.73%,3839.0000,3935.000,3778.000,3834.0000,2 002,18.09 23:43
28,NaN,Microsoft,15200,-0.71%,15320.0000,15426.000,14880.000,15309.0000,1 739,18.09 23:21
29,NaN,Netflix,35575,0.06%,35719.0000,36050.000,34800.000,35555.0000,292,18.09 23:09

In [4]:
#Выведем на экран
df.head()

,Unnamed: 0,Инструмент,"Посл. сделка, ₽",% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,+МосЭнергоПотенциал:+7%,2.045 ₽,-0.7%,2.062,2.101,2.045,2.0595,35 483 000,18.09 18:45
1,NaN,Activision,6087,3.7%,5881.000,6088.000,5881.000,5870.0000,742,18.09 23:39
2,NaN,AGRO-гдрПотенциал:+24%,743.4 ₽,-0.59%,750.000,753.800,740.400,747.8000,39 456,18.09 18:49
3,NaN,Amazon,221813,-2.37%,220500.000,229466.000,220500.000,227200.0000,100,18.09 22:02
4,NaN,AMD Inc.,5685,-1.22%,5747.000,5840.000,5599.000,5755.0000,3 295,18.09 23:38

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       0 non-null      float64
 1   Инструмент       30 non-null     object
 2   Посл. сделка, ₽  30 non-null     object
 3   % Изм. цены      30 non-null     object
 4   Открытие         29 non-null     float64
 5   Макс.            29 non-null     float64
 6   Мин.             29 non-null     float64
 7   Закрытие         30 non-null     float64
 8   Объем, шт.       29 non-null     object
 9   Время обн.       30 non-null     object
dtypes: float64(5), object(5)
memory usage: 2.5+ KB

In [6]:
#Проанализируем изменение цены. min() max()
df['% Изм. цены'] = df.apply(lambda row: row['% Изм. цены'][:-1], axis=1)
df['% Изм. цены'] = df['% Изм. цены'].astype('float')

In [7]:
df['% Изм. цены'].min()

-2.99